### ISSUE TITLE
How to run API server http://localhost:3001?

### ISSUE THREAD

**Issue by tesicg** [wfro/parsnip#4]
Hello,

I'm trying to run your samples, but, for example, when I open "CH6", I usually do:

- npm install
- npm start

But, after the application starts I've got the page with "Network Error" at the top.

I suppose I need to run API server on: http://localhost:3001, but it doesn't start.

What should I do to run your samples on my local machine?

Thank you in advance.

**Comment by wolovim** [comment]
Hey @tesicg! First, thanks for reading.

The API server details are in the appendix (page 274, at least in the physical book). Short version: `json-server` gets installed globally, then you can run it with: `json-server --watch db.json --port 3001` in a separate terminal window. Let us know if you still have trouble.

**Comment by tesicg** [comment]
Yes. I've found it and all is easy and everything works fine.

The book is excellent!

Thanks a lot!

**Comment by wolovim** [comment]
Glad to hear! Thank you!

**Comment by JaguarHeartz** [comment]
im trying to run my website but it ait opening anywher
